name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Lint and build (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Show versions
        run: |
          python --version
          uv --version

      - name: Install dependencies (with dev)
        run: uv sync --dev

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Build sdist and wheel
        run: uv build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
          if-no-files-found: error


